updates

diff --git a/.github/workflows/stinkbait-build.yaml b/.github/workflows/stinkbait-build.yaml
--- a/.github/workflows/stinkbait-build.yaml
+++ b/.github/workflows/stinkbait-build.yaml
@@ -67,10 +67,15 @@ jobs:
         with:
           role-to-assume: arn:aws:iam::225609042289:role/github-action-role
           aws-region: us-east-1
-      - name: Get stack events
+      - name: Check CloudFormation stack events
         run: |
-          aws cloudformation describe-stack-events --stack-name <stack-name> | grep "CREATE_FAILED" | tee >(cat >&2)
-          echo $? # 0 if no failed events, 1 if there are failed events
+          failed_events=$(aws cloudformation describe-stack-events --stack-name $STACK_NAME --query "StackEvents[?ResourceStatus=='CREATE_FAILED']")
+          echo "$failed_events" >> failed_events.log
+          if [ -n "$failed_events" ]; then
+            echo "The following CREATE_FAILED events were found:"
+            echo "$failed_events"
+            exit 1
+          fi
       - name: Package Lambda Function Code
         run: aws cloudformation package --template-file template.yaml --s3-bucket stinkbait-225609042289 --output-template-file packaged_template.yaml --region us-east-1
       - name: Deploy the CloudFormation Stack
